[package]
name = "vipn"
version = "0.1.0"
authors = ["mswift42 <martin.haesler@gmail.com>"]

[dependencies]
select = "0.4.2"
url = "1.7.0"
reqwest = "0.8.4"
serde = "1.0.14"
serde_json = "1.0"
serde_derive = "1.0"
failure = "0.1.1"
